load(strcat("parameters_job_no_", num2str(job_no), ".mat"), ...
            'parameters');
result = fun(parameters{:});
save(strcat("result_job_no_", num2str(job_no), ".mat"), ...
            'result');
