universe      = vanilla
Executable    = execute_matlab_script.py
arguments     = -i test.m 1D_16xLC_c0_mu_hom
Log           = matlab_test.log
error         = matlab_test.err
output        = matlab_test.txt
requirements  = ((Machine!="MAXWELL.uni-muenster.de") && (Machine!="THOMSON.uni-muenster.de"))
notification  = Never
getenv        = true
rank          = kflops
transfer_input_files    = sys_cont_pars.m, test.m, SimpleLaser_Compare.m, sys_rhs.m, stationary.m, sys_start.m, sys_tau.m, sys_init.m, sys_deri.m, sys_ndde.m, sys_cond.m
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Queue
